---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
    dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
  labels:
    tenant: Dolittle
    application: Studio
  name: application-e08c0a4d-1133-402f-ad6a-07fa1aba4718

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
    dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
  labels:
    tenant: Dolittle
    application: Studio
    environment: Prod
  name: prod-tenants
  namespace: application-e08c0a4d-1133-402f-ad6a-07fa1aba4718
data:
  tenants.json: |
    {
        "491ba108-2f0c-472e-8693-b224d1ad9dbc": {}
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
    dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
    dolittle.io/microservice-id: 99354d00-0be1-422a-963f-6c2f9273c369
  labels:
    tenant: Dolittle
    application: Studio
    environment: Prod
    microservice: SelfService
  name: prod-selfservice-dolittle
  namespace: application-e08c0a4d-1133-402f-ad6a-07fa1aba4718
data:
  appsettings.json: |
    {
        "Logging": {
            "IncludeScopes": false,
            "LogLevel": {
                "Default": "Debug",
                "System": "Information",
                "Microsoft": "Information"
            },
            "Console": {
                "IncludeScopes": true,
                "TimestampFormat": "[yyyy-MM-dd HH:mm:ss] "
            }
        },
        "dolittle": {
            "runtime": {
                "eventStore": {
                    "backwardscompatibility": {
                        "version": "V7"
                    }
                }
            }
        }
    }
  clients.json: |
    {
        "public": {
            "host": "localhost",
            "port": 50052
        },
        "private": {
            "host": "localhost",
            "port": 50053
        }
    }
  endpoints.json: |
    {
        "public": {
            "port": 50052
        },
        "private": {
            "port": 50053
        },
        "management": {
            "port": 51052
        }
    }
  event-horizon-consents.json: |
    {
    }
  event-horizons.json: |
    [
    ]
  microservices.json: |
    {
    }
  platform.json: |-
    {
        "applicationName": "Studio",
        "applicationID": "e08c0a4d-1133-402f-ad6a-07fa1aba4718",
        "microserviceName": "SelfService",
        "microserviceID": "99354d00-0be1-422a-963f-6c2f9273c369",
        "customerName": "Dolittle",
        "customerID": "556b3d97-2030-4b0a-92b4-9122606b6127",
        "environment": "Prod"
    }
  resources.json: |
    {
        "491ba108-2f0c-472e-8693-b224d1ad9dbc": {
          "readModels": {
            "host": "mongodb://prod-mongo:27017",
            "database": "99354d0_491ba10_readmodels",
            "useSSL": false
          },
          "eventStore": {
            "servers": [
              "prod-mongo"
            ],
            "database": "99354d0_491ba10_eventstore"
          },
          "embeddings": {
            "servers": [
              "prod-mongo"
            ],
            "database": "99354d0_491ba10_embeddings"
          },
          "projections": {
            "servers": [
              "prod-mongo"
            ],
            "database": "99354d0_491ba10_projections"
          }
        }
      }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
    dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
    dolittle.io/microservice-id: 99354d00-0be1-422a-963f-6c2f9273c369
  labels:
    tenant: Dolittle
    application: Studio
    environment: Prod
    microservice: SelfService
  name: prod-selfservice
  namespace: application-e08c0a4d-1133-402f-ad6a-07fa1aba4718
spec:
  replicas: 1
  selector:
    matchLabels:
      tenant: Dolittle
      application: Studio
      environment: Prod
      microservice: SelfService
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
        dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
        dolittle.io/microservice-id: 99354d00-0be1-422a-963f-6c2f9273c369
      labels:
        tenant: Dolittle
        application: Studio
        environment: Prod
        microservice: SelfService
    spec:
      containers:
        - name: head
          image: nginxdemos/hello:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/.dolittle/tenants.json
              name: tenants-config
              subPath: tenants.json
            - mountPath: /app/.dolittle/resources.json
              name: dolittle-config
              subPath: resources.json
            - mountPath: /app/.dolittle/clients.json
              name: dolittle-config
              subPath: clients.json
            - mountPath: /app/.dolittle/event-horizons.json
              name: dolittle-config
              subPath: event-horizons.json
        - name: runtime
          image: dolittle/runtime:8.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
              name: runtime
            - containerPort: 9700
              name: runtime-metrics
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/.dolittle/tenants.json
              name: tenants-config
              subPath: tenants.json
            - mountPath: /app/.dolittle/resources.json
              name: dolittle-config
              subPath: resources.json
            - mountPath: /app/.dolittle/endpoints.json
              name: dolittle-config
              subPath: endpoints.json
            - mountPath: /app/.dolittle/event-horizon-consents.json
              name: dolittle-config
              subPath: event-horizon-consents.json
            - mountPath: /app/.dolittle/microservices.json
              name: dolittle-config
              subPath: microservices.json
            - mountPath: /app/appsettings.json
              name: dolittle-config
              subPath: appsettings.json
            - mountPath: /app/.dolittle/platform.json
              name: dolittle-config
              subPath: platform.json
        - name: shell
          image: studio-terminal:local
          imagePullPolicy: Never
          ports:
            - containerPort: 7681
              name: shell
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /home/studio/.dolittle/tenants.json
              name: tenants-config
              subPath: tenants.json
            - mountPath: /home/studio/.dolittle/resources.json
              name: dolittle-config
              subPath: resources.json
            - mountPath: /home/studio/.dolittle/clients.json
              name: dolittle-config
              subPath: clients.json
            - mountPath: /home/studio/.dolittle/endpoints.json
              name: dolittle-config
              subPath: endpoints.json
            - mountPath: /home/studio/.dolittle/event-horizon-consents.json
              name: dolittle-config
              subPath: event-horizon-consents.json
            - mountPath: /home/studio/.dolittle/event-horizons.json
              name: dolittle-config
              subPath: event-horizons.json
            - mountPath: /home/studio/.dolittle/microservices.json
              name: dolittle-config
              subPath: microservices.json
            - mountPath: /home/studio/appsettings.json
              name: dolittle-config
              subPath: appsettings.json
            - mountPath: /home/studio/.dolittle/platform.json
              name: dolittle-config
              subPath: platform.json
      volumes:
        - configMap:
            defaultMode: 420
            name: prod-tenants
          name: tenants-config
        - configMap:
            defaultMode: 420
            name: prod-selfservice-dolittle
          name: dolittle-config

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
    dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
  labels:
    tenant: Dolittle
    application: Studio
    environment: Prod
    infrastructure: Mongo
  name: prod-mongo
  namespace: application-e08c0a4d-1133-402f-ad6a-07fa1aba4718
spec:
  selector:
    tenant: Dolittle
    application: Studio
    environment: Prod
    infrastructure: Mongo
  clusterIP: None
  ports:
    - port: 27017
      targetPort: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
    dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
  labels:
    tenant: Dolittle
    application: Studio
    environment: Prod
    infrastructure: Mongo
  name: prod-mongo
  namespace: application-e08c0a4d-1133-402f-ad6a-07fa1aba4718
spec:
  selector:
    matchLabels:
      tenant: Dolittle
      application: Studio
      environment: Prod
      infrastructure: Mongo
  serviceName: prod-mongo
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dolittle.io/tenant-id: 556b3d97-2030-4b0a-92b4-9122606b6127
        dolittle.io/application-id: e08c0a4d-1133-402f-ad6a-07fa1aba4718
      labels:
        tenant: Dolittle
        application: Studio
        environment: Prod
        infrastructure: Mongo
    spec:
      containers:
        - name: mongo
          image: dolittle/mongodb:4.2.2
          ports:
            - name: mongo
              containerPort: 27017
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
